### ISSUE TITLE
4.1.8 causes crash bug

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#237] opened 2019-05-31 20:55 UTC
when damage is done to dude and the source is not a critter,crashes,such as the goo on ground in arroyo gardens,and bridgekeeper special event,tried with 4.1.7 with bridgekeeper and it does not crash

**Comment by nirran** [comment] 2019-05-31 21:12
to make sure,i deleted my combatdamge hook script and tried,it also crashed on goo

**Comment by nirran** [comment] 2019-05-31 21:46
also tried emptying the scripts folder(i have megamod packed into master dat),still crashed

**Comment by NovaRain** [comment] 2019-05-31 23:53
What is the crash message? Does it also happen with 3.8.18?
I tried the goo in Arroyo and called `critter_dmg(dude_obj, 1000, (DMG_normal_dam BWOR DMG_BYPASS_ARMOR));` in a keypress hook script, and both worked normally.

**Comment by nirran** [comment] 2019-06-01 00:22
the message is "address could not be read 0239abc9 with 8.1.8

here is my ini
https://www.wowhead.com/achievement=12997/the-pride-of-kul-tiras#comments

023a56a3 with 3.8.18

**Comment by NovaRain** [comment] 2019-06-01 00:37
Have you tried checking in vanilla or RP without packing the whole megamod in master.dat?

**Comment by nirran** [comment] 2019-06-01 00:39
ill load with vanilla master,be a min

**Comment by nirran** [comment] 2019-06-01 00:44
boo,it doens t erro,problem is in megamod,sorry

**Comment by FakelsHub** [comment] 2019-06-01 01:47
what is the reason? If 4.1.7 does not cause the crash of the game, then obviously some bug appeared in 4.1.8.
Did you find out what the reason for the error was?

**Comment by nirran** [comment] 2019-06-01 01:52
Donno What it is,i thogth i narrowed it to [code]critter_dmg(source_obj, random(1, 3), 3);[/code]

but even with the script from vanilla it crashes,i am now checking if it has anythign to do with it being packed into master dat

**Comment by nirran** [comment] 2019-06-01 02:08
lame,when packed into master dat it crashes,if i dont pack it doesnt,leads me to suspect it has to do with priority of files ie : patch00->data->master

**Comment by NovaRain** [comment] 2019-06-01 02:15
Is it the same with DataLoadOrderPatch=1?

**Comment by nirran** [comment] 2019-06-01 02:36
yep,crashes with 0 and 1

**Comment by NovaRain** [comment] 2019-06-01 03:41
Guess we'll have to do some more tests. Since the crash happens on 4.1.8/3.8.18 but not 4.1.7/3.8.17, I made some versions of ddraw.dll with different new fixes/features disabled: 
https://www.mediafire.com/file/7tuy5393e7k1s5c/ddraw_tests.rar/file

See if there's a version that doesn't crash. Hope this can pinpoint the cause.

**Comment by FakelsHub** [comment] 2019-06-01 06:30
disable the ExtraKillTypes option and check.

**Comment by nirran** [comment] 2019-06-01 15:02
nogo with all 3 tests and killtypes

**Comment by NovaRain** [comment] 2019-06-01 15:26
> 
> 
> nogo with all 3 tests and killtypes

OK, here are another three for testing. I took commits between 4.1.7 and 4.1.8 as checkpoints.
https://www.mediafire.com/file/725c0ldn25sfdx7/ddraw_test2.rar/file

**Comment by nirran** [comment] 2019-06-01 16:00
crashed with all 3

**Comment by FakelsHub** [comment] 2019-06-01 16:07
Send your master.dat with packed script.

**Comment by nirran** [comment] 2019-06-01 16:17
too large for this site,send email

**Comment by nirran** [comment] 2019-06-01 17:30
bump in case u missed the upload

**Comment by nirran** [comment] 2019-06-01 17:43
correction,i tested with a save that had dude one hex away from goo,if i load tht save it crashe son goo,if i load save of dude right before argarden,it crashes

**Comment by nirran** [comment] 2019-06-01 17:46
sam,e exact behavior wiht bridgekeeper,load w/o save before talk crashes,with save does not crash

**Comment by nirran** [comment] 2019-06-01 18:33
double checked previous sfall,4.1.7 ,and doesnt crash with save or w.o save

**Comment by nirran** [comment] 2019-06-01 20:47
ok to reproduce the big,dl this data folder to fo2/data(and the mm and critter files i sent earlier) and go to goo in argarden,after deleting city and maps.txt in data data folder,it doesnt happen,i believe it has something to do with the sfallm edits

https://www.mediafire.com/file/msy6h82jz5mirm1/Data.7z/file

**Comment by FakelsHub** [comment] 2019-06-01 22:05
I solve the problem.

**Comment by nirran** [comment] 2019-06-01 22:08
yay

**Comment by nirran** [comment] 2019-06-01 22:08
what was it?

**Comment by FakelsHub** [comment] 2019-06-01 22:58
Some script in megamod with functions set_weapon_knockback, set_target_knockback, set_attacker_knockback contains a bug. and plus an old bug in the sfall, triggering the game crash.
When starting a new or re-save game no longer have such a bug, as bug in your save.

**Comment by nirran** [comment] 2019-06-01 23:15
glad u found and fixed it,seems i forgot to delte hs_ scripts when i packed megamod,it is actualy a script i wrote,thnx again

**Comment by NovaRain** [comment] 2019-06-01 23:16
That's weird. Between commit f788246 (first commit after 4.1.7) and 42cf5de there are no changes to those functions, but 4.1.7 doesn't trigger the bug?

**Comment by nirran** [comment] 2019-06-01 23:21
it was related to a hook script packed into master dat,and maybe jumped the gun closing?tho i did verify,i repacked master dat w/o the hs_scripts and checked,no crashes

**Comment by nirran** [comment] 2019-06-01 23:26
no 4.1.7 did not have the bug,and i verified no crash with all sfall global and hook scripts deleted or moved,no crash

**Comment by FakelsHub** [comment] 2019-06-01 23:42
No, with the HS_Tohit.int script, everything is fine there.
This is a bug in sfall.

**Comment by nirran** [comment] 2019-06-01 23:46
glad it is fixed,great job guys

**Comment by NovaRain** [comment] 2019-06-01 23:49
> 
> 
> No, with the HS_Tohit.int script, everything is fine there.
> This is a bug in sfall v4.1.4

I'm curious. You mean a bug in 4.1.4 (and 3.8.14?) got fixed in 4.1.8? What was it?

**Comment by FakelsHub** [comment] 2019-06-02 00:18
> but 4.1.7 doesn't trigger the bug?

This also has such an bug.

**Comment by NovaRain** [comment] 2019-06-02 00:31
> 
> 
> > but 4.1.7 doesn't trigger the bug?
> 
> This also has such an bug.
> You can release version 4.1.8.1

So it's just lucky that 4.1.7 didn't trigger it?
And it seems you're mean to include it for 4.1.9?

**Comment by nirran** [comment] 2019-06-02 00:43
Good With 3x and 4x versions,no crashes

**Comment by FakelsHub** [comment] 2019-06-02 00:50
So it's just lucky that 4.1.7 didn't trigger it?
And it seems you're mean to include it for 4.1.9, maybe I should just wait until then?

why, and with 4.1.7 game crash.
At you discretion.

**Comment by NovaRain** [comment] 2019-06-02 00:59
> 
> why, and with 4.1.7 game crash.
> At you discretion.

Oh, OK. If you still don't plan to do more commits in these days (since you said you're working on some stuff), I'll make a hotfix release today. It seems hotfix usually happen on even numbers of releases.

**Comment by FakelsHub** [comment] 2019-06-02 01:13
No more commits..

**Closed** 2019-06-03 01:38 UTC
