### ISSUE TITLE
A couple of bugs in Hero Appearance mod

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#94] opened 2017-04-23 17:03 UTC
1. When loading a game saved with custom appearance (e.g. long hair dude), PC will be in default appearance instead of the custom one. This bug is in sfall 3.8.2 and later. Looks like it might have something to do with changing the load order of sfallgv.sav. The related sfall global variables did get saved in sfallgv.sav, but they are not loaded properly or something.
2. (sfall 4.0 dev only) AppStyle.frm & AppRace.frm didn't get displayed in character screen.

**Comment by phobos2077** [comment] 2017-04-24 09:39
Fixed in both 3.8 and 4.0 branches. Need to confirm.

**Comment by Lexx2k** [comment] 2017-04-24 12:31
Do you have a new dll file flying around? Can't compile stuff on my own. :>

**Comment by phobos2077** [comment] 2017-04-24 12:48
Do you need 3.8 or 4.0 version?

**Comment by Lexx2k** [comment] 2017-04-24 12:54
The latest - 4.0 - thanks!

**Comment by phobos2077** [comment] 2017-04-24 17:31
Strange, I didn't encounter any delays. The only code that could potentially introduce delays (loading FRMs from disk) wasn't changed, only rewritten a bit but it does exactly the same thing.

**Comment by NovaRain** [comment] 2017-04-24 23:28
I didn't notice any delay when loading a save with custom appearance. What's the spec of your PC?

**Comment by Lexx2k** [comment] 2017-04-25 06:46
Dont have the specs off the top of my head, but it's pretty far up top, with quad core and all that jazz. It's a bit weird because the game runs a bit slow at times anyway- starting the game takes like half a minute, for example (till the program starts). On my other pc the game starts instantly, so I don't belive it is related to some global scripts.

**Comment by phobos2077** [comment] 2017-04-25 06:49
The game starts for about 1 to 20 seconds for me. I believe it is related to some direct input issue. It happened before I even got on board. Can you clarify when exactly the hiccups happen? Do you use scripts to change character appearance? Can you post the code?

**Comment by Lexx2k** [comment] 2017-04-25 07:48
No, I dont use any scripts related to changing the look of the character or similar. It's really just happening after loading a savegame. Not sure right now if it also happens after map change- i guess you wouldnt notice here, as the screen stays black for a moment longer. I'll take a look at it once i am back home today-- disabling all global scripts, etc.

**Comment by Lexx2k** [comment] 2017-04-25 14:25
Just tried without any global scripts running and no change. Whenever I load the game, I see the graphic flip for about a second. It is NOT noticeable on map change, though, which I find way more important. So yeah, I dunno... Personally, I wouldn't rate it as very problematic as of now.

**Comment by phobos2077** [comment] 2017-04-25 16:34
What do you mean by graphic flip? You can see dude appearance being changed after a second? I think I know how to fix that (by remaking LoadGame_after hook so it is called before anything is drawn on screen).

**Comment by Lexx2k** [comment] 2017-04-25 16:40
Yes, that's what I mean. You see normal dude after loading a game, then about a second later he changes to the "correct" one: bald head, long hair, green hair, etc.

**Comment by burner1024** [comment] 2017-05-02 11:08
Hi, guys. Don't want to hijack, but is there any ETA on 4.0 release?

**Comment by phobos2077** [comment] 2017-05-03 06:56
@burner1024 , I think we can release it next weekend. It will still be marked as beta and recommended for modders until enough users test it for bugs.

**Comment by phobos2077** [comment] 2017-05-20 11:12
@Lexx2k, can you check if the issue can be seen with this build https://yadi.sk/d/8Kpj_hw_3JMHMx ?

**Comment by Lexx2k** [comment] 2017-05-20 14:01
Appears to switch faster now. If I really try then I can still see the graphic switch. Wouldn't call it a very serious issue, though.

**Comment by NovaRain** [comment] 2017-05-20 15:48
Just curious, does this switching display issue also happen on 3.8.x?

**Comment by Lexx2k** [comment] 2017-05-21 07:01
I just tested a few versions... was quite annoying, as starting the game is so slow.

sfall_3.8.4.7z - graphic flip is visible
sfall_3.8.3.7z - doesn't work at all (the known bug)
sfall_3.8.2.7z - doesn't work
sfall_3.8.1.7z - graphic flip is visible
sfall_3.7.4.7z - graphic flip is visible too...
...

Alright, looks like this one is on me. Apparently it was always there? I've never noticed it before at all...

**Comment by phobos2077** [comment] 2017-05-21 08:27
Ok I guess it should be good enough now. On normal fast system the switch shouldn't be noticeable at all.

**Closed by phobos2077** 2017-05-21 08:27 UTC
Labels: bug

**Comment by Lexx2k** [comment] 2017-05-21 08:34
But what do you consider a "'normal' fast system"? :D 
I run an Intel Core i5-6600K with a GeForce GTX970 and 16gb of Ram. There is rarely anything that makes problems, especially Fallout 2 shouldn't, imo. :p

**Comment by NovaRain** [comment] 2017-05-21 09:15
I'd guess the issue is probably more software related than hardware, given that on my test machines which are slower than yours don't have the issue.

**Comment by burner1024** [comment] 2017-05-21 20:41
I can confirm the flip on 3.8.4 but can't see one in ddraw_20170520.
