### ISSUE TITLE
open and close inventory in combat crashes fo2

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#151] opened 2018-05-14 23:30 UTC
started a new game with sfall 4.0.4,and this happened,able to reproduce but sometimes it doesnt crash,thought it was a mod of mine but played with it for a while and found that sfall 3.8.8 does not crash this at all,pretty reliable,tried all sfall 4.0 versions,same thing,odly enough a save I have of lvl 50~ it doesn't happen,in fact ive only seen it in temple of trials,on the ants,thinking it only happens on empty critters dead,and btw it happens only when a dead body is on the ground

**Comment by NovaRain** [comment] 2018-05-14 23:43
What's the error message of the crash? I can't reproduce the crash here. And please make sure you're not playing the game with your mods.

**Comment by nirran** [comment] 2018-05-15 00:09
did more testing and found that it only happens when the critter has no loot,i used an addon to add loot to all critters and could not reproduce the crash using this method,also I loaded the game without any global or hook scripts and it still crashed

"the instruction at 0048bf67 referenced memory at 02a8f138 the memory could not be written click ok to terminate the application"

**Comment by FakelsHub** [comment] 2018-05-15 00:44
Please upload your game on the file exchanger (w/o critter.dat & master.dat), to me to find out the reason for the crash of the game.

**Comment by nirran** [comment] 2018-05-15 00:55
what exactly do I upload?

**Comment by NovaRain** [comment] 2018-05-15 01:36
Since your download link isn't working, I just installed Megamod 2.45.3 and updated sfall to 4.0.4, but still can't get the crash when I killed a giant ant and opened/closed inventory in combat.

**Comment by nirran** [comment] 2018-05-15 01:41
I changed permissions,should be able to dl it now

**Comment by NovaRain** [comment] 2018-05-15 01:46
By "not working" I mean it requires me to login, which I don't have an account and didn't want to register one.

**Comment by nirran** [comment] 2018-05-15 01:55
ok try this one

http://www.nirran.com/FTP/Fallout%202.7z

**Comment by FakelsHub** [comment] 2018-05-15 01:58
it seems to me that the problem is in the OS
what system do you have?

**Comment by nirran** [comment] 2018-05-15 02:00
windows 10 is my main,this is run inside win xp virtual box tho

**Comment by FakelsHub** [comment] 2018-05-15 02:03
Win10 bad system)))

**Comment by nirran** [comment] 2018-05-15 02:04
problem with winxp or the host win10?

**Comment by NovaRain** [comment] 2018-05-15 02:05
>windows 10 is my main,this is run inside win xp virtual box tho

I have no idea why you would do that, as FO2+sfall can work perfectly fine in Win10.

**Comment by nirran** [comment] 2018-05-15 02:05
figured it would be outdated for new OS and wanted a permanent place for fo2

**Comment by nirran** [comment] 2018-05-15 02:07
gona copy it to win10,thnx for the help

**Comment by FakelsHub** [comment] 2018-05-15 02:12
> FO2+sfall can work perfectly fine in Win10.

win10 has some problems with fallout, win7 best os for fallout game

**Comment by nirran** [comment] 2018-05-15 21:27
after running it in win10,no longer have the crash bug

**Comment by NovaRain** [comment] 2018-05-16 01:39
Then it's more like Virtual Box's problem, because I didn't get the crash in WinXP in VMware. I'll close this issue.

**Closed by NovaRain** 2018-05-16 01:39 UTC
