### ISSUE TITLE
Crash with create_win()

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#376] opened 2021-05-10 09:48 UTC
In the past weeks I have noticed that there is a crash related to creating a new window.

Example code to reproduce:
```
// gl_slidetest.ssl
 
#include ".\headers\define.h"
#include ".\headers\command.h"
#include ".\headers\sfall\sfall.h"
#include ".\headers\sfall\define_extra.h"
#include ".\headers\sfall\dik.h"
 
#define EVENT_SLIDESHOW       (3)
 
variable Slide;
 
procedure start;
procedure timed_event_p_proc;
procedure KeyPressHandler;
 
procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
   end
end
 
procedure KeyPressHandler begin
   variable
      event := get_sfall_arg,
      keyDX := get_sfall_arg,
      keyVK := get_sfall_arg;
 
   if (keyDX == DIK_V) then begin
      if event then begin
         add_global_timer_event(5, EVENT_SLIDESHOW);
         display_msg("Start slideshow timer event.");
      end
   end
end
 
// emulate the crash bug in Et Tu junkdemo.ssl
procedure timed_event_p_proc begin
   if (fixed_param == EVENT_SLIDESHOW) then begin
      add_global_timer_event(game_ticks(3), EVENT_SLIDESHOW); // 3 sec for each
      reg_anim_clear(dude_obj);
      if (Slide == 0) then begin
         game_ui_disable;
         Slide := 1;
         create_win("win_slide", 0, 0, get_screen_width, get_screen_height);
         SelectWin("win_slide");
         ShowWin;
      end
      else if (Slide == 1) then begin
         Slide := 2;
         win_fill_color(0, 0, get_screen_width, get_screen_height, 40);
      end
      else if (Slide == 2) then begin
         Slide := 3;
         win_fill_color(0, 0, get_screen_width, get_screen_height, 152);
      end
      else if (Slide == 3) then begin
         //gfade_out(ONE_GAME_SECOND);
         DeleteWin("win_slide");
         game_ui_enable;
         //load_map(MAP_HOTEL, 69);
      end
   end
end
```

Just start a new game/load a save, press V key. After the fake slideshow is finished, (re)load a save and press V again. The game will now crash.

I have also experienced this crash related to our water timer note in the PipBoy. However, this one does not reliably crash ... I'm not 100% sure what is triggering it. Sometimes I can keep pressing the P button for a minute to quickly open/close the PipBoy and nothing bad will happen. Sometimes I reload a game, open the PipBoy and the game dies on it.

**Comment by NovaRain** [comment] 2021-05-10 14:12
For the pipboy crash, here are the steps to reproduce it:
Open the pipboy -> **click** the timer note -> close the pipboy and (re)load a save -> try to **hover** the cursor over the timer note -> crash.

And it seems the crash is caused by the fix for `checkAllRegions_` function in 4.2.9, as after removing the fix the crash is gone.

**Comment by FakelsHub** [comment] 2021-05-11 00:45
> For the pipboy crash, here are the steps to reproduce it:

not reproduce. 
what is "timer note"?

**Comment by NovaRain** [comment] 2021-05-11 01:05
> 
> 
> > For the pipboy crash, here are the steps to reproduce it:
> 
> not reproduce.
> what is "timer note"?

The "XXX Days Left" note on the pipboy:
![piptimer](https://user-images.githubusercontent.com/8564973/117742704-e03d6f00-b237-11eb-9697-87c71c01e7f1.png)

**Comment by FakelsHub** [comment] 2021-05-11 01:52
> Example code to reproduce:

Learn how to write scripts correctly.

**Comment by NovaRain** [comment] 2021-05-11 01:55
> 
> 
> > Example code to reproduce:
> 
> Learn how to write scripts correctly.

Can you give a more detail explanation on what's wrong in the example?

**Comment by FakelsHub** [comment] 2021-05-11 02:14
> how to correct it?

use SelectWin before using win functions.

**Comment by FakelsHub** [comment] 2021-05-11 03:28
where the crash occurs?
for me all good.

**Comment by Lexx2k** [comment] 2021-05-11 08:44
There is another issue: ettu TMA will crash on start if mode=0 is set in ddraw.ini. At this point it only works in Dx9 mode for some reason. I could swear that wasn't the case before?

**Comment by NovaRain** [comment] 2021-05-12 12:51
According to Lexx's test, now trying to return the value of -1 in KeyPress hook will crash the game if sfall's DX9 mode is not enabled.
It was not the case before commit e99fe09.

**Comment by NovaRain** [comment] 2021-05-13 04:28
OK, because the crash in the first post is solved, I'll close this issue.
Not sure about the crash with keypress return value in non-DX9 setup, tried some larger values like 50000 also crash, maybe there should be some kind of limit/trimming for the return value? Supposedly the max value of a scancode is 255 (0xFF)?

**Closed by NovaRain** 2021-05-13 04:28 UTC
Labels: bug, scripting

**Comment by FakelsHub** [comment] 2021-05-14 20:27
in my sfall `set_sfall_return(-1)` does not cause an error.

**Comment by NovaRain** [comment] 2021-05-14 22:02
> in my sfall `set_sfall_return(-1)` does not cause an error.

Are you using DX9 mode? The crash only happens when _not_ using it.

**Comment by FakelsHub** [comment] 2021-05-14 23:35
DX9 off

**Comment by NovaRain** [comment] 2021-05-14 23:45
> 
> 
> DX9 off

Weird, I tested the script with your build and it still crashed.

**Comment by FakelsHub** [comment] 2021-05-15 01:39
try
```
void __stdcall ForceGraphicsRefresh(DWORD d) {
	if (!d3d9Device) return;
	forcingGraphicsRefresh = (d == 0) ? 0 : 1;
}
```

**Comment by FakelsHub** [comment] 2021-05-15 01:51
You have some kind of compiler glitch that doesn't compile the code correctly.

**Comment by NovaRain** [comment] 2021-05-15 01:56
> 
> 
> You have some kind of compiler/code glitch that doesn't compile the code correctly.

Compiler is updated to the latest version, and for your build I didn't touch any code.
Here's the build from my compiler and the script: [sfallext_70ee64e.zip](https://github.com/phobos2077/sfall/files/6481742/sfallext_70ee64e.zip)

**Comment by FakelsHub** [comment] 2021-05-15 02:09
the variable  forcingGraphicsRefresh contains a garbage value, it is likely that the dimension/size of something is broken somewhere.

**Comment by NovaRain** [comment] 2021-05-15 02:21
> 
> 
> the variable forcingGraphicsRefresh contains a garbage value, it is likely that the dimension/size of something is broken somewhere.

Shouldn't it be only 0 or 1? The only things I can think of are KeyDown and keysDown[] in InputFunc.cpp.

**Comment by FakelsHub** [comment] 2021-05-15 02:23
probably going beyond the bounds of the keysDown array
then I'll put debugging assets

**Comment by FakelsHub** [comment] 2021-05-15 02:27
keysDown[-1]  :-)

**Comment by FakelsHub** [comment] 2021-05-15 02:38
by the way, what prompted you to use -1 in this hook, nothing is said about this value in the description.

**Comment by NovaRain** [comment] 2021-05-15 02:47
> 
> 
> keysDown[-1] :-)

Given that KeyDown takes DWORD key, I guess it might be keysDown[4294967295]?
Maybe just put a limit (0-263) on the return value in KeyPress hook?

> 
> 
> by the way, what prompted you to use -1 in this hook, nothing is said about this value in the description.

It was Lexx wanted to [override the keys to something else in Et Tu's TMA script](https://github.com/rotators/Fo1in2/blob/1e2c1e8204ea229f3298979659fa60f1c2feb92e/Fallout2/Fallout1in2/Mapper/source/scripts/GlobalScripts/gl_tma.ssl#L203 ).
The strange thing is that it didn't crash before implementing IniReader module/class, and it doesn't crash in 3.8 (or not yet to cause the crash?)

**Comment by Lexx2k** [comment] 2021-05-15 05:49
I just wanted to return nothing, and values from 0 to 255 are always _something_. Even if it's not specifically needed.

**Comment by FakelsHub** [comment] 2021-05-15 07:56
you have address conflicts in ettu, so you need to review your magic hacks.

**Comment by FakelsHub** [comment] 2021-05-15 08:02
> It was Lexx wanted to override the keys with something else in Et Tu's TMA script.

This is some kind of stupidity, it just needs to be removed.

> The strange thing is that it didn't crash before implementing IniReader

This is somewhere-buggy in another place, just lucky that t this time it got on the variable.

**Comment by NovaRain** [comment] 2021-05-15 08:22
> 
> 
> > It was Lexx wanted to override the keys with something else in Et Tu's TMA script.
> 
> This is some kind of stupidity, it just needs to be removed.

He changed the script to return 255 instead (0xFF should be reserved so nothing will happen) and the crash is gone. It's just me still curious how the problem happened and if there's some way to prevent/fix the crash if others do the same thing in the future.

> 
> > The strange thing is that it didn't crash before implementing IniReader
> 
> This is somewhere-buggy in another place, just lucky that t this time it got on the variable.

Maybe, it's not the first time similar cases happen (stuff that "supposedly" work is actually glitched, just not being triggered yet).

**Comment by Lexx2k** [comment] 2021-05-15 09:55
> you have address conflicts in ettu, so you need to review your magic hacks.

Yeah, or maybe it's an issue in Sfall. Can you stop being such an arrogant piece of shit sometimes?

**Comment by FakelsHub** [comment] 2021-05-15 11:24
Crashes and errors have nothing to do with it. sfall reports that there are conflicts in your game.

**Comment by NovaRain** [comment] 2021-05-15 11:43
> 
> 
> Crashes and errors have nothing to do with it. sfall reports that there are conflicts in your game.

You mean when using dev build?

BTW, here's the video showing the crash in RP:
[![](http://img.youtube.com/vi/U-Buu2B5nT0/0.jpg)](https://www.youtube.com/watch?v=U-Buu2B5nT0 "KeyPress hook crash in non-DX9 mode")
