### ISSUE TITLE
A bug with Hero Appearance Mod

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#309] opened 2020-06-06 22:06 UTC
If you go through pregenerated characters, stop at a female character and then press Create Character, it will retain female appearance as the default state for a male character

![scr00000](https://user-images.githubusercontent.com/58548291/83955382-43659b00-a84a-11ea-8d1c-b6da6375b72f.jpg)

**Comment by NovaRain** [comment] 2020-06-07 03:44
I suppose moving this line to below `endFunc:` label should be enough:
https://github.com/phobos2077/sfall/blob/703073e25598ee6f63a6ac9733e67730f84c77dc/sfall/Modules/HeroAppearance.cpp#L476

**Comment by FakelsHub** [comment] 2020-06-07 12:44
it may be necessary to clarify.

**Comment by NovaRain** [comment] 2020-06-07 13:49
> 
> 
> it may be necessary to clarify.

It's easy to reproduce. New Game -> switch to Chitsa -> Create Character. The character window will still display default female appearance instead of male. Moving the `call proto_dude_update_gender_` line down seems to fix the glitch.

**Comment by FakelsHub** [comment] 2020-06-07 15:47
> Moving the call proto_dude_update_gender_ line down seems to fix the glitch.

I mean, it's definitely this place, not somewhere else.
ps: I'm not going to code anything in sfall yet, I still have other tasks.

**Comment by NovaRain** [comment] 2020-06-07 16:19
> 
> I mean, it's definitely this place, not somewhere else.

Oh, I thought the glitch is due to player's gender doesn't get updated/reset when clicking Create Character, and CreateCharReset() seems to be the best bet. So I just changed it to always call proto_dude_update_gender no matter the result of checking currentStyle/RaceVal.

**Comment by FakelsHub** [comment] 2020-06-07 16:27
but currentStyle/RaceVal do not change so I thought that the bug is somewhere else, because without the mod, the floor is restored without additional functions proto_dude_update_gender_

**Closed** 2020-06-14 01:31 UTC
