### ISSUE TITLE
Vertibird Mod by Den Buster don't work with (last?) sFall

### ISSUE THREAD

**Issue by johnnyd-78** [phobos2077/sfall#374] opened 2021-05-07 22:52 UTC
Hi!

With last sFall when I try to fly to any location screen fade in and then stay blank. If I press F1 (help screen) then Esc - I see the game and can play, but don't see vertibird. If turn off sFall all works fine.
I try set CarChargingFix=0 and CarPlacedTileFix=0 but it don't help. May be it must be did before start new game?

Any ideas/fixes?

**Comment by NovaRain** [comment] 2021-05-08 00:03
There are multiple versions or the one included in Megamod or such, which one you're using?

**Comment by johnnyd-78** [comment] 2021-05-08 00:59
I don't know nothing about Megamod or other versions of VM, sorry. It just Vertibird Mod by Denis Balikhin (aka Den Buster) - russian Vertibird Mod included in patch/mod Fallout 2 v1.03Y.

**Comment by FakelsHub** [comment] 2021-05-08 02:13
1. need your save.
2. need mod files.

**Comment by NovaRain** [comment] 2021-05-08 03:03
I grabbed the version with "v1.30Y Final 06.07.2006" label and tried to make some edits on vertibird scripts, but since I don't play the mod, the edit was more or less a guess work.

You can try the edited scripts: [vertimod_fix_test.zip](https://github.com/phobos2077/sfall/files/6445054/vertimod_fix_test.zip)
Extract the scripts to your Data\scripts\ folder, backup the existing ones first if they are in the folder.

It seems the cause is similar to the ending bug in UP/RP: timed event in one script affected by calling `game_time_advance` in another.

**Comment by johnnyd-78** [comment] 2021-05-08 03:41
> You can try the edited scripts: vertimod_fix_test.zip

Thanks! I tried but no effect, still blank screen and no vertibird in "travel" location

**Comment by johnnyd-78** [comment] 2021-05-08 03:44
My save... https://dropmefiles.com/AiWg4

**Comment by FakelsHub** [comment] 2021-09-16 07:41
the save files were deleted and the mod files were not provided.
Close the issue with the wont-fix label.

**Closed** 2021-09-16 11:56 UTC
