### ISSUE TITLE
AllowLargeTiles produces glitched tiles

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#367] opened 2021-04-15 20:03 UTC
I tried cutting a big tile using AllowLargeTiles but all it produced was a bunch of glitched smaller FRMs. Not sure what I could be doing wrong here.

**Comment by FakelsHub** [comment] 2021-04-15 20:46
so show the produce result.
this has never been used by anyone. :)

**Comment by blackpaulillyria** [comment] 2021-04-15 20:55
Hehe oh yeah, I can see it has never been used :)

Here's an example. I took altar1.frm and it produced only those 3 zzz frms.
[tiles.zip](https://github.com/phobos2077/sfall/files/6321067/tiles.zip)

**Comment by FakelsHub** [comment] 2021-04-15 23:44
everything is clear, you used bullshit and the algorithm produced bullshit for you.

**Comment by blackpaulillyria** [comment] 2021-04-16 05:50
> everything is clear, you used bullshit and the algorithm produced bullshit for you.
> the size must be observed `80*sizeX, 36*sizeY`

OK but the sfall documentation is the only bullshit here. Why do I have to look into the sfall source code to figure out what must be exactly done? That's the real reason here no one used this before.

**Comment by Lexx2k** [comment] 2021-04-16 06:14
I always thought the big tiles must be at least as big as a normal tile. Without measuring it, though, I'm pretty sure your example graphic doesn't fit that dimensions.

**Comment by blackpaulillyria** [comment] 2021-04-16 06:49
Can't get this to work properly even after setting the size to conform to 80*sizeX, 36*sizeY rule. I'll have to cut this using Photoshop

**Comment by Lexx2k** [comment] 2021-04-16 06:59
Can you show a screenshot from inside the game?

**Comment by blackpaulillyria** [comment] 2021-04-16 07:29
> Can you show a screenshot from inside the game?

You mean show spoilers heheee :)
Here it is, it's not finished I just started cutting it using Photoshop and making great progress. Think you can figure out from the screenshot what it is ;)

![scr00072](https://user-images.githubusercontent.com/58548291/114988111-da997700-9e8d-11eb-9aaa-0ba819b8e82a.png)

**Comment by Lexx2k** [comment] 2021-04-16 07:39
But it looks like the tiles are working?

I meant, show screenshot of the broken stuff.

**Comment by blackpaulillyria** [comment] 2021-04-16 10:15
> But it looks like the tiles are working?
> 

Yes those are all small tiles but I cut those with Photoshop, not with sfall.

> I meant, show screenshot of the broken stuff. Also keep in mind that big tiles ofc will not work in the mapper.

You can see examples of broken tiles here (from my posts above) https://github.com/phobos2077/sfall/files/6321067/tiles.zip

**Comment by FakelsHub** [comment] 2021-04-16 18:57
A very strange algorithm, when parsing it, it turned out that it cuts according to this principle:
![w](https://user-images.githubusercontent.com/21695363/115071299-c2157500-9efe-11eb-9d9f-bdaa1901f052.jpg)
tiles that are marked in green, that is, only those that fall completely into the grid.

And I don't understand how it should all look on the map, despite the fact that this has not worked for a long time with 3.7 and possibly older versions.

**Comment by NovaRain** [comment] 2021-04-17 00:08
Maybe it was designed for chopping tiles graphics that's just like an extra large version of normal tiles, that graphics inside the square shape area, or like a merged tile set.

**Closed** 2021-04-26 12:26 UTC
