### ISSUE TITLE
party members forget levels

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#233] opened 2019-04-13 19:32 UTC
is it possible to alter the engines handling of base proto to make it not set the coresponding save/proto.pro read only?would eliminate a big problem

**Comment by FakelsHub** [comment] 2019-04-13 23:06
Describe the problem in more detail.

**Comment by nirran** [comment] 2019-04-13 23:24
ok - when the base party member proto is in data/proto/critters,the engine saves a copy of it to the save folder,and if the pro file is read only(as it has to be),the save folder copy of the pro file is also set to read only,and when the party member levels up,the engine tries to copy the new lvl proto to the save/ pro file of the base party member,and fails because it is set to read only,thus when the pro is read and loaded,it reverts to base pro party stats

**Comment by NovaRain** [comment] 2019-04-13 23:25
I think the problem is related to putting party member's base protos in the protos folder instead of inserting them in DAT.

**Comment by nirran** [comment] 2019-04-13 23:25
yes nova,that is the bug i am talking about

**Comment by FakelsHub** [comment] 2019-04-14 01:51
Ok.

> I think the problem is related to putting party member's base protos in the protos folder instead of inserting them in DAT.

This has been fixed in the Crafty version. And to keep the base proto in dates is optional.

**Comment by FakelsHub** [comment] 2019-04-14 02:48
Basic prototypes of party members should not be placed in the data folder!
That is the architecture of the engine, and this is not fix.
Close.

**Comment by FakelsHub** [comment] 2019-04-14 02:48
Basic prototypes of party members should not be placed in the data folder!
That is the architecture of the engine, and this is not fix.
Close.

**Closed** 2019-04-14 10:37 UTC

**Comment by FakelsHub** [comment] 2019-04-22 16:12
Perhaps in the next versions I will do so that the prototypes of the party .members  are stored in memory, and not on the disk.

**Comment by burner1024** [comment] 2019-07-09 07:02
This should no longer be an issue with new DataLoadOrder, right?

**Comment by NovaRain** [comment] 2019-07-09 07:04
The fix is not related to DataLoadOrder. But yes it's not an issue anymore after 4.1.8.

**Comment by burner1024** [comment] 2019-07-09 07:05
ok, great.
