### ISSUE TITLE
fake perks in 4.1.6

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#232] opened 2019-04-12 19:53 UTC
4.1.6 sfall has error when selecting multiple fake perks,it sets the known perk to multiple lines of the same perk,instead of

"Here And Now Perks(2)"

it has

"Here And Now Perks"
"Here And Now Perks"

and as such the "has_fake_perk" function returns one when it should be 2

**Comment by FakelsHub** [comment] 2019-04-13 02:33
Show Screenshot.
Is this not really the engine perk "Here And Now"?  The name is strange.

**Comment by nirran** [comment] 2019-04-13 03:12
it is a fake perk i wrote

**Comment by NovaRain** [comment] 2019-04-13 05:02
Does that only happen on 4.1.6, not 3.8.16 or older sfall versions?

**Comment by nirran** [comment] 2019-04-13 15:03
not with earlier versions

**Comment by NovaRain** [comment] 2019-04-13 23:54
OK, the issue is fixed in the coming 4.1.7. It was due to a minor coding error.

**Closed by NovaRain** 2019-04-13 23:54 UTC

**Comment by nirran** [comment] 2019-04-13 23:59
yay thnx
